//
//  Constant.h
//  UCB_POC
//
//  Created by Saurabh on 8/9/16.
//  Copyright © 2016 Amit. All rights reserved.
//

#import <Foundation/Foundation.h>

@interface Constant : NSObject
FOUNDATION_EXPORT NSString *const EWS_REQUSET_URL;
FOUNDATION_EXPORT NSString *const EWS_REQUSET_EMAIL_ID;
FOUNDATION_EXPORT NSString *const EWS_USERS_PASSWORD;
FOUNDATION_EXPORT NSString *const EWS_REQUSET_USERID;

FOUNDATION_EXPORT NSString *const EWS_REQUSET_USERID_KEY;
FOUNDATION_EXPORT NSString *const EWS_USERS_PASSWORD_KEY;

FOUNDATION_EXPORT NSString *const GET_DETAILS_BEACON_API;
FOUNDATION_EXPORT NSString *const TIPS_CATEGORY_API;
FOUNDATION_EXPORT NSString *const NEWS_API;

FOUNDATION_EXPORT NSString *const BASE_URL;

FOUNDATION_EXPORT NSString *const RENDER_DOC_API;

FOUNDATION_EXPORT NSString *const NEWS_CATEGORY_API;
FOUNDATION_EXPORT NSString *const LATEST_NEW_ID_API;


@end
